// Static build: bundles TS/CSS with Bun, renders every page in src/pages/registry.ts, and writes the
// Cloudflare Pages files into dist/.
//   bun run build            → dist/ (placeholders allowed, listed at the end)
//   bun run build:strict     → fails while any required placeholder in site.config.ts is unfilled
//   SITE_URL=https://… bun run build   → one-off origin override

import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { config, missingRequired, pendingLaunch } from "../site.config";
import { faviconSvg } from "../src/lib/mark";
import { ARTS, PHOTOS, SHOTS } from "../src/pages/images";
import type { Assets, ImgAsset } from "../src/pages/layout";
import { OG, ogFile } from "../src/pages/og";
import { updated } from "../src/pages/dates";
import { PAGES } from "../src/pages/registry";

export const ROOT = join(import.meta.dir, "..");
export const DIST = join(ROOT, "dist");
const STATIC = join(ROOT, "static");
const ASSOCIATION = ".well-known/apple-app-site-association";
const ASSOCIATION_PATHS = ["/open", "/open/*", "/help/*", "/session"];

async function verifyAssociationSource() {
  const source = await readFile(join(STATIC, ASSOCIATION), "utf8");
  const launch = await readFile(join(ROOT, "../Docs/launch/apple-app-site-association"), "utf8");
  if (source !== launch) throw new Error("Website AASA differs from Docs/launch/apple-app-site-association");
  const details = JSON.parse(source)?.applinks?.details;
  if (!Array.isArray(details) || details.length !== 1 ||
      JSON.stringify(details[0]?.appIDs) !== JSON.stringify(["39HM2X8GS6.com.roshan.PocketDesk.Remote"]) ||
      JSON.stringify(details[0]?.components?.map((entry: { "/"?: string }) => entry["/"])) !== JSON.stringify(ASSOCIATION_PATHS) ||
      details[0].components.some((entry: object) => Object.keys(entry).length !== 1)) {
    throw new Error("Website AASA must contain only the approved Farside app ID and routes");
  }
}

const ENTRIES = ["home", "site"] as const;

export function csp(styleHashes: string[]) {
  return [
    "default-src 'none'",
    "script-src 'self'",
    `style-src 'self' ${styleHashes.map((h) => `'${h}'`).join(" ")} https://fonts.googleapis.com`,
    "font-src https://fonts.gstatic.com",
    "img-src 'self' data:",
    "connect-src 'self'",
    "manifest-src 'self'",
    "base-uri 'none'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "object-src 'none'",
    "upgrade-insecure-requests",
    "require-trusted-types-for 'script'",
    // No script writes HTML strings, so no Trusted Types policy may be created at all.
    "trusted-types 'none'",
  ].join("; ");
}

function headersFile(styleHashes: string[]) {
  return `# Cloudflare Pages response headers. Generated by scripts/build.ts; edit there, not here.
/*
  Content-Security-Policy: ${csp(styleHashes)}
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()
  Cross-Origin-Opener-Policy: same-origin

# Content-hashed bundles and images never change, so browsers may keep them for a year.
/assets/*
  Cache-Control: public, max-age=31536000, immutable

/og/*
  Cache-Control: public, max-age=86400
/favicon.ico
  Cache-Control: public, max-age=86400
/icon.svg
  Cache-Control: public, max-age=86400
/apple-touch-icon.png
  Cache-Control: public, max-age=86400
/icon-192.png
  Cache-Control: public, max-age=86400
/icon-512.png
  Cache-Control: public, max-age=86400
/site.webmanifest
  Content-Type: application/manifest+json
  Cache-Control: public, max-age=86400
/llms.txt
  Content-Type: text/plain; charset=utf-8

# Apple fetches this extensionless file directly; its response must be JSON with no redirect.
/.well-known/apple-app-site-association
  Content-Type: application/json

# Keep the *.pages.dev hostnames out of search results; only the custom domain should be indexed.
https://:project.pages.dev/*
  X-Robots-Tag: noindex
https://:version.:project.pages.dev/*
  X-Robots-Tag: noindex
`;
}

function redirectsFile() {
  const mac = config.launch.macDownloadUrl ?? "/#beta";
  const app = config.launch.appStoreUrl ?? "/#beta";
  return `# Cloudflare Pages redirects. Generated by scripts/build.ts; edit there, not here.
# Pages already maps /page.html to /page and serves 404.html for unknown paths.
/privacy-policy        /privacy                    301
/terms-of-use          /terms                      301
/tos                   /terms                      301
/eula                  /terms                      301
/legal                 /terms                      301
/help                  /support                    301
/contact               /support#contact            301
/faq                   /#faq                       301
/pricing               /#pricing                   301
/guides                /#guides                    301
/vs                    /compare                    301
/comparison            /compare                    301
/control-mac           /control-mac-from-iphone    301
/trackpad              /iphone-as-mac-trackpad     301
/remote-desktop        /remote-desktop-for-mac     301
/beta                  /#beta                      302
/download              /#beta                      302
/mac                   ${mac}  302
/download/mac/latest   ${mac}  302
/app                   ${app}  302
`;
}

function sitemapFile() {
  const urls = PAGES.filter((p) => p.sitemap)
    .map((p) => `  <url><loc>${config.SITE_URL}${p.path}</loc><lastmod>${updated(p.path)}</lastmod></url>`)
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

function robotsFile() {
  return `User-agent: *
Allow: /

Sitemap: ${config.SITE_URL}/sitemap.xml
`;
}

/** llms.txt (llmstxt.org): a plain summary and link list for language models reading the site. */
function llmsFile() {
  const P = config.pricing;
  const R = config.requirements;
  const section = (name: string) =>
    PAGES.filter((p) => p.llms?.section === name)
      .map((p) => `- [${p.llms!.title}](${config.SITE_URL}${p.path}): ${p.llms!.note}`)
      .join("\n");
  return `# Farside

> Farside lets you see and control your own Mac from your iPhone or iPad. The whole screen is a trackpad with click haptics, a big sharp pointer drawn by the phone, zoom that follows the pointer, voice dictation into the Mac and a clipboard that goes both ways. Pairing is a QR code approved on the Mac, with no account, and everything is encrypted end to end. Farside is in beta and coming soon to the App Store; anyone can join the beta at ${config.SITE_URL}/#beta.

Key facts:

- Free on the same local network as the Mac, with no account and no ads.
- The Anywhere plan adds access over the internet through an encrypted relay: ${P.final ? "" : "planned at "}${P.monthly} a month or ${P.yearly} a year, with a ${P.trialDays}-day free trial, sold only inside the iPhone and iPad app through Apple.
- Farside for Mac (the companion that runs on the Mac) will be a free download from this website, signed with an Apple Developer ID and notarized by Apple. Farside for iPhone and iPad will be on the App Store.
- Planned requirements: ${R.mac}; ${R.iphone}; ${R.ipad}.
- "Agent needs you" alerts for AI coding agents running on the Mac arrive as a beta; alerts carry no prompts, file names or screen content.
- Limits: Macs only (no Windows, Linux or Android); one Mac display at a time; no audio; the Mac must be awake and logged in; no pressure gestures.
- The website sets no cookies and runs no analytics.
- Farside (getfarside.com) is not related to farside.app or to other products with a similar name.

## Main

- [Home](${config.SITE_URL}/): what Farside does, how it works, features, pricing, FAQ, beta sign-up
- [About](${config.SITE_URL}/about): who makes Farside, what it is, how to get in touch

## Guides

${section("Guides")}

## Help

${section("Help")}

## Legal

${section("Legal")}
`;
}

function manifestFile() {
  return JSON.stringify(
    {
      name: "Farside",
      short_name: "Farside",
      description: "See and control your own Mac from your iPhone or iPad.",
      start_url: "/",
      display: "browser",
      background_color: "#050505",
      theme_color: "#050505",
      icons: [
        { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
        { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
        { src: "/icon.svg", sizes: "any", type: "image/svg+xml" },
      ],
    },
    null,
    2,
  );
}

/** Launch day (config.launch.live): the App Store badge must be Apple's official artwork, dropped in by hand. */
async function checkLaunch() {
  if (!config.launch.live) return;
  if (!(await Bun.file(join(STATIC, "app-store-badge.svg")).exists())) {
    throw new Error("launch.live is on but static/app-store-badge.svg (Apple's official badge) is missing");
  }
  if (!config.launch.appStoreId || !config.launch.appStoreUrl) throw new Error("launch.live needs launch.appStoreId and launch.appStoreUrl");
}

const hash8 = (data: ArrayBuffer | Uint8Array | string) => new Bun.CryptoHasher("sha256").update(data).digest("hex").slice(0, 8);
const sha256b64 = (text: string) => new Bun.CryptoHasher("sha256").update(text).digest("base64");

async function bundle(out: string) {
  const js = await Bun.build({
    entrypoints: ENTRIES.map((e) => join(ROOT, "src/scripts", `${e}.ts`)),
    outdir: join(out, "assets"),
    naming: "[name]-[hash].[ext]",
    target: "browser",
    format: "esm",
    minify: true,
    splitting: false,
    sourcemap: "none",
  });
  if (!js.success) throw new AggregateError(js.logs, "JavaScript bundle failed");
  const jsMap = {} as Assets["js"];
  for (const o of js.outputs) {
    if (o.kind !== "entry-point") continue;
    const file = basename(o.path);
    jsMap[file.replace(/-[a-z0-9]+\.js$/, "") as keyof Assets["js"]] = `/assets/${file}`;
  }
  for (const e of ENTRIES) if (!jsMap[e]) throw new Error(`missing bundle for ${e}`);

  // CSS is bundled in memory and inlined: site.css into every page, home.css (the hero demo and the home
  // sections) only into the home page.
  const sheet = async (file: string) => {
    const css = await Bun.build({ entrypoints: [join(ROOT, "src/styles", file)], minify: true });
    if (!css.success) throw new AggregateError(css.logs, `CSS bundle failed: ${file}`);
    const cssOut = css.outputs.find((o) => o.path.endsWith(".css"));
    if (!cssOut) throw new Error(`no CSS output for ${file}`);
    const text = (await cssOut.text()).trim();
    if (text.includes("</style")) throw new Error("CSS must not contain </style");
    return text;
  };
  return { js: jsMap, cssText: await sheet("site.css"), homeCss: await sheet("home.css") };
}

/** Design-preview images: copied into /assets/img with content hashes, sizes from static/img/manifest.json. */
async function images(out: string): Promise<Record<string, ImgAsset>> {
  const manifestFile = Bun.file(join(STATIC, "img/manifest.json"));
  if (!(await manifestFile.exists())) return {};
  const manifest = (await manifestFile.json()) as Record<string, { w: number; h: number }>;
  await mkdir(join(out, "assets/img"), { recursive: true });
  const map: Record<string, ImgAsset> = {};
  for (const a of ARTS) {
    const m = manifest[a.key];
    const src = Bun.file(join(STATIC, `img/${a.key}.${a.ext}`));
    if (!m || !(await src.exists())) continue;
    const data = await src.arrayBuffer();
    const name = `${a.key}-${hash8(data)}.${a.ext}`;
    await Bun.write(join(out, "assets/img", name), data);
    map[a.key] = { src: `/assets/img/${name}`, src2x: `/assets/img/${name}`, w: m.w, h: m.h };
  }
  for (const s of SHOTS) {
    const m = manifest[s.key];
    if (!m) continue;
    const names: string[] = [];
    for (const suffix of ["", "@2x"]) {
      const src = Bun.file(join(STATIC, `img/${s.key}${suffix}.webp`));
      if (!(await src.exists())) throw new Error(`missing static/img/${s.key}${suffix}.webp; run bun run assets`);
      const data = await src.arrayBuffer();
      const name = `${s.key}${suffix === "@2x" ? "-2x" : ""}-${hash8(data)}.webp`;
      await Bun.write(join(out, "assets/img", name), data);
      names.push(`/assets/img/${name}`);
    }
    map[s.key] = { src: names[0]!, src2x: names[1]!, w: m.w, h: m.h };
  }
  // Real app screenshots at several widths, for srcset with width descriptors.
  for (const p of PHOTOS) {
    const files: [number, string][] = [];
    for (const width of p.widths) {
      const src = Bun.file(join(STATIC, `img/${p.key}-${width}.webp`));
      if (!(await src.exists())) throw new Error(`missing static/img/${p.key}-${width}.webp`);
      const data = await src.arrayBuffer();
      const name = `${p.key}-${width}-${hash8(data)}.webp`;
      await Bun.write(join(out, "assets/img", name), data);
      files.push([width, `/assets/img/${name}`]);
    }
    map[p.key] = {
      src: files[0]![1],
      src2x: files[files.length - 1]![1],
      w: p.w,
      h: p.h,
      srcset: files.map(([w, u]) => `${u} ${w}w`).join(", "),
    };
  }
  return map;
}

async function ogVersions(): Promise<Record<string, string>> {
  const map: Record<string, string> = {};
  for (const o of OG) {
    const f = Bun.file(join(STATIC, ogFile(o.key)));
    const v = (await f.exists()) ? hash8(await f.arrayBuffer()) : "dev";
    map[o.key] = `/${ogFile(o.key)}?v=${v}`;
  }
  return map;
}

export async function build(opts: { outDir?: string; quiet?: boolean } = {}) {
  const out = opts.outDir ?? DIST;
  const helpPages = PAGES.filter((p) => p.path === "/help" || p.path.startsWith("/help/"));
  if (helpPages.length) throw new Error(`pages under /help/ would open the app (AASA): ${helpPages.map((p) => p.path).join(", ")}; use /support/…`);
  await verifyAssociationSource();
  await rm(out, { recursive: true, force: true });
  await mkdir(join(out, "assets"), { recursive: true });

  const b = await bundle(out);
  await cp(STATIC, out, { recursive: true, filter: (src) => !src.includes(`${join(STATIC, "img")}`) });
  const assets: Assets = { cssText: b.cssText, homeCss: b.homeCss, js: b.js, og: await ogVersions(), img: await images(out) };
  const styleHashes = [b.cssText, b.homeCss].map((t) => `sha256-${sha256b64(t)}`);
  await checkLaunch();

  const pages: Record<string, string> = {};
  for (const p of PAGES) pages[p.file] = p.render(assets);
  const files: Record<string, string> = {
    ...pages,
    "icon.svg": faviconSvg(),
    "robots.txt": robotsFile(),
    "sitemap.xml": sitemapFile(),
    "llms.txt": llmsFile(),
    "site.webmanifest": manifestFile(),
    _headers: headersFile(styleHashes),
    _redirects: redirectsFile(),
  };
  await Promise.all(Object.entries(files).map(([name, body]) => writeFile(join(out, name), body)));

  if (!opts.quiet) {
    const missing = missingRequired();
    const pending = pendingLaunch();
    console.log(`built ${Object.keys(pages).length} pages → ${out}`);
    console.log(`  css inlined: site ${(b.cssText.length / 1024).toFixed(1)} KB, home +${(b.homeCss.length / 1024).toFixed(1)} KB`);
    for (const [k, v] of Object.entries(assets.js)) console.log(`  js  ${k}: ${v}`);
    console.log(`  images ${Object.keys(assets.img).length}, og cards ${Object.values(assets.og).filter((v) => !v.endsWith("=dev")).length}/${OG.length}`);
    console.log(`  SITE_URL ${config.SITE_URL}`);
    if (missing.length) console.log(`  placeholders still to fill (site.config.ts): ${missing.join(", ")}`);
    if (pending.length) console.log(`  not set yet (site shows "Coming soon"/placeholders): ${pending.join(", ")}`);
  }
  return { out, assets, styleHashes };
}

if (import.meta.main) {
  if (process.argv.includes("--strict")) {
    const missing = missingRequired();
    if (missing.length) {
      console.error(`build:strict refused: fill these in site.config.ts first → ${missing.join(", ")}`);
      process.exit(1);
    }
  }
  const i = process.argv.indexOf("--out");
  await build({ outDir: i > -1 ? process.argv[i + 1] : undefined, quiet: process.argv.includes("--quiet") });
}
