// Generates src/styles/fallbacks.css: local fallback faces whose metrics are tuned to Geist, Geist Mono,
// Doto and Instrument Serif, so the swap from fallback to web font moves nothing (CLS 0).
// Measured in headless Chrome with the real Google Fonts files. Re-run after changing fonts:
//   bun scripts/font-metrics.ts

import { join } from "node:path";
import { FONTS_URL } from "../src/pages/layout";
import { launch } from "./chrome";
import { ROOT } from "./build";

type Face = { family: string; weight: number; style: "normal" | "italic"; measure: string; local: string[]; fallbackName: string; weightRange: string };

const FACES: Face[] = [
  { family: "Geist", weight: 400, style: "normal", measure: "Arial", local: ["Arial", "ArialMT", "Helvetica", "Roboto"], fallbackName: "Geist Fallback", weightRange: "100 500" },
  { family: "Geist", weight: 600, style: "normal", measure: "Arial", local: ["Arial Bold", "Arial-BoldMT", "Helvetica Bold", "Roboto Bold"], fallbackName: "Geist Fallback", weightRange: "501 900" },
  { family: "Geist Mono", weight: 400, style: "normal", measure: "Courier New", local: ["Courier New", "CourierNewPSMT", "Menlo", "Roboto Mono"], fallbackName: "Geist Mono Fallback", weightRange: "100 900" },
  { family: "Doto", weight: 800, style: "normal", measure: "Courier New", local: ["Courier New Bold", "CourierNewPS-BoldMT", "Courier New", "Menlo"], fallbackName: "Doto Fallback", weightRange: "100 900" },
  { family: "Instrument Serif", weight: 400, style: "italic", measure: "Times New Roman", local: ["Times New Roman Italic", "TimesNewRomanPS-ItalicMT", "Times New Roman", "Georgia Italic"], fallbackName: "Instrument Serif Fallback", weightRange: "100 900" },
];

const SAMPLE =
  "Farside puts your Mac on your iPhone or iPad and turns the whole screen into a trackpad. One finger points. A tap clicks. No account, no cables, no awkward lunge across the couch. How it works, Features, Pricing, Support, Join the beta.";

const browser = await launch();
const page = await browser.newPage();
await page.setContent(`<!doctype html><html><head><link rel="stylesheet" href="${FONTS_URL.replace("&display=swap", "&display=block")}"></head><body></body></html>`, {
  waitUntil: "load",
});

const results: string[] = [];
for (const f of FACES) {
  const m = await page.evaluate(
    async (f, SAMPLE) => {
      const measure = (family: string) => {
        const c = document.createElement("canvas").getContext("2d")!;
        c.font = `${f.style} ${f.weight} 100px ${family}`;
        const t = c.measureText(SAMPLE);
        const div = document.createElement("div");
        div.style.cssText = `font:${f.style} ${f.weight} 100px ${family};line-height:normal;position:absolute;white-space:nowrap`;
        div.textContent = "Hxgy";
        document.body.appendChild(div);
        const h = div.getBoundingClientRect().height;
        div.remove();
        return { width: t.width / 100, ascent: t.fontBoundingBoxAscent / 100, descent: t.fontBoundingBoxDescent / 100, normal: h / 100 };
      };
      await document.fonts.load(`${f.style} ${f.weight} 100px "${f.family}"`, SAMPLE);
      const web = measure(`"${f.family}"`);
      const fb = measure(`"${f.measure}"`);
      return { web, fb, local: f.measure };
    },
    f,
    SAMPLE,
  );
  const size = m.web.width / m.fb.width;
  const pct = (v: number) => `${(v * 100).toFixed(2)}%`;
  const lineGap = Math.max(0, m.web.normal - m.web.ascent - m.web.descent);
  results.push(
    `/* ${f.family} ${f.weight} ${f.style}: measured against ${m.local} */
@font-face {
  font-family: "${f.fallbackName}";
  src: ${f.local.map((n) => `local("${n}")`).join(", ")};
  font-style: ${f.style};
  font-weight: ${f.weightRange};
  size-adjust: ${pct(size)};
  ascent-override: ${pct(m.web.ascent / size)};
  descent-override: ${pct(m.web.descent / size)};
  line-gap-override: ${pct(lineGap / size)};
}`,
  );
  console.log(f.family, f.weight, f.style, "via", m.local, { size: size.toFixed(4), ...m.web });
}
await browser.close();

const out = join(ROOT, "src/styles/fallbacks.css");
await Bun.write(
  out,
  `/* Generated by scripts/font-metrics.ts. Local fallback faces tuned to the web fonts' metrics so the
   font-display: swap moment does not move layout. */\n\n${results.join("\n\n")}\n`,
);
console.log(`wrote ${out}`);
