// Copies the approved hero demo ("A2") from the hero lab into src/hero-a2/.
//   bun scripts/sync-hero-a2.ts ../design/hero-lab/src/a2
// a2.html and a2.css are copied unchanged. a2.js is the lab script with three mechanical edits so it runs as
// a module under this site's CSP: an import of the lab helpers it expects (src/hero-a2/env.ts), its two
// innerHTML writes wrapped in a Trusted Types policy, and an export of initA2.

import { join } from "node:path";

const from = process.argv[2];
if (!from) {
  console.error("usage: bun scripts/sync-hero-a2.ts <path to design/hero-lab/src/a2>");
  process.exit(1);
}
const to = join(import.meta.dir, "../src/hero-a2");

for (const f of ["a2.html", "a2.css"]) await Bun.write(join(to, f), Bun.file(join(from, f)));

let js = await Bun.file(join(from, "a2.js")).text();
const sinks = js.match(/\.innerHTML = \w+;/g) ?? [];
if (sinks.length !== 2) throw new Error(`expected 2 innerHTML writes in a2.js, found ${sinks.length}; check the Trusted Types wrapping`);
js = js.replace(/\.innerHTML = (\w+);/g, ".innerHTML = trustedHTML($1);");
if (!/function initA2\(\)/.test(js)) throw new Error("a2.js no longer defines initA2()");
js =
  "// Generated by scripts/sync-hero-a2.ts from design/hero-lab/src/a2/a2.js. Edit the lab copy, then re-sync.\n" +
  'import { RM, clamp, ease, paused, stage, trustedHTML, tween, wait, waiters } from "./env";\n\n' +
  js.trimEnd() +
  "\n\nexport { initA2 };\n";
await Bun.write(join(to, "a2.js"), js);
console.log(`synced a2.html, a2.css, a2.js → ${to}`);
