// All social copy. Rules: no launch date, no latency/user numbers, no ratings or testimonials, no prices,
// "Anywhere" is always "coming", "agent needs you" is always "beta", never "the far side". Brand tag: #farsideapp.
export const LINK = "[LINK]";

export const BIOS = {
  x: { limit: 160, items: [
    "Your Mac is far. Your reach isn't. Farside turns your iPhone into your Mac's trackpad. Free on the same Wi-Fi. Beta list below.",
    "See and control your Mac from iPhone or iPad. The whole screen is a trackpad and it clicks back. No account. Built in public with AI agents.",
    "Remote control for your own Mac, from your iPhone. Big sharp pointer, voice typing, clipboard both ways. Last reached 11:48 PM. We won't ask why.",
  ] },
  instagram: { limit: 150, items: [
    "Your Mac is far. Your reach isn't.\nControl your Mac from iPhone: the whole screen is a trackpad.\nFree on the same Wi-Fi · beta list ↓",
    "Your iPhone, your Mac's trackpad. Big pointer, voice typing, clipboard both ways. No account needed. Beta list ↓",
    "Remote control for your own Mac. A serious pointer, a deadpan app. Free on your own Wi-Fi. Beta ↓",
  ] },
  tiktok: { limit: 80, items: [
    "Your Mac is far. Your reach isn't. Control your Mac from iPhone ↓",
    "Your iPhone is now your Mac's trackpad. Beta list ↓",
    "Controlling my Mac from the couch. Built with AI agents.",
  ] },
  threads: { limit: 150, note: "Threads can import the Instagram bio and avatar; use Instagram option 1.", items: [] },
};

export const HANDLES = [
  ["farsideapp", "X, Instagram, Threads, TikTok", "First choice: one handle everywhere, reads as the app"],
  ["getfarside", "all four", "Matches the proposed domain getfarside.com"],
  ["farside.app", "Instagram, Threads, TikTok (dots not allowed on X)", "Clean on IG/TikTok; pair with farsideapp on X"],
  ["farside_app", "all four", "Fallback if farsideapp is taken"],
  ["usefarside", "all four", "Common SaaS pattern"],
  ["tryfarside", "all four", "Matches the defensive domain tryfarside.com"],
  ["farsidehq", "all four", "Brand-account feel"],
  ["heyfarside", "all four", "Friendly fallback"],
];

export const PROFILE = {
  displayName: "Farside",
  displayNameAlt: "Farside · Mac remote",
  link: "Use one link everywhere once the domain exists (getfarside.com is proposed, not registered). Until then: a simple beta-list page. X: website field + first reply. Instagram: up to 5 bio links. TikTok: a bio link needs a Business account (or 1,000 followers). Threads: shares the Instagram profile link.",
  pins: {
    x: "Pin the launch post with the V01 contact video (16:9).",
    instagram: "Pin 3: V01 contact Reel, C3 “How Farside works in 3 taps”, P15 beta list.",
    threads: "Pin the intro post (P01).",
    tiktok: "Pin 3: V01 contact, V04 someone is controlling your Mac, V06 agent needs you.",
  },
};

const H = {
  ig: ["#farsideapp", "#macos", "#iphone", "#productivity", "#buildinpublic"],
  tt: ["#farsideapp", "#mac", "#iphonetips", "#techtok", "#buildinpublic"],
};

export const POSTS = {
  "post-01": { title: "Reach hero", series: "Reach", plat: "Instagram feed 4:5 (also X, Threads)",
    ig: "Your Mac is far. Your reach isn't.\n\nFarside lets you see and control your Mac from your iPhone. The whole screen becomes a trackpad. Slide to point, tap to click, and your phone clicks back.\n\nFree on the same Wi-Fi. Beta list in bio.",
    x: "Your Mac is far. Your reach isn't.\n\nFarside: see and control your Mac from your iPhone. The whole screen is a trackpad.",
    threads: "Your Mac is far. Your reach isn't. We're building Farside: your iPhone becomes your Mac's trackpad. What would you do from the couch first?",
    tag: "Mac", hashtags: H.ig,
    alt: "Halftone hand reaching a big pixel pointer, an orange dot where they touch. Your Mac is far." },
  "post-02": { title: "Big pointer energy", series: "Closes the gap", plat: "Instagram 1:1 (also X, Threads)",
    ig: "Big pointer energy.\n\nFarside draws a big, sharp pointer right on your phone, so you're not squinting at a shrunken Mac cursor from across the room.\n\nControl your Mac from iPhone. Beta list in bio.",
    x: "Big pointer energy.\n\nFarside draws the pointer on your phone: big, sharp, and exactly where you left it.",
    threads: "Big pointer energy. That's the post.", tag: "Mac", hashtags: H.ig,
    alt: "A big crisp mouse pointer with an orange tip and dotted orange rings. Big pointer energy." },
  "post-03": { title: "Talk to your phone", series: "Closes the gap", plat: "Instagram 4:5 (also X, Threads)",
    ig: "Talk to your phone. It types on your Mac.\n\nTap the mic, say it, tap Done. The words land wherever your Mac's cursor is, even in a rename field.\n\nVoice dictation into your Mac, from your iPhone.",
    x: "Talk to your phone. It types on your Mac.\n\nEven \"final final v2\".",
    threads: "Talk to your phone, it types on your Mac. What's the worst file name you've ever dictated?", tag: "Mac", hashtags: H.ig,
    alt: "A listening card with a dot sound wave above a rename field reading final final v2." },
  "post-04": { title: "Copy here. Paste there.", series: "Closes the gap", plat: "X 16:9",
    x: "Copy here. Paste there.\n\nFarside's clipboard works both ways: iPhone to Mac and Mac to iPhone.",
    threads: "Clipboard both ways: copy on your iPhone, paste on your Mac. And back.", tag: "Mac", ig: null, hashtags: ["#farsideapp"],
    alt: "An iPhone with a Copy button and a Mac mail window with a Paste button, joined by dotted arrows both ways. Text: Copy here. Paste there." },
  "post-05": { title: "Your agent needs you (beta)", series: "Agent needs you · beta", plat: "X 16:9",
    x: "Your agent needs you.\n\nWhen your AI coding agent stops to ask a question, Farside taps you on the shoulder. Answer from your phone. Beta.",
    threads: "Beta feature: when your coding agent stops to ask permission, your phone taps you. What do you let your agents do without asking?", tag: "AI", ig: null, hashtags: ["#buildinpublic"],
    alt: "A terminal asking to allow the agent to run tests, next to a phone notification that says Your agent needs you, with Deny and Allow buttons." },
  "post-06": { title: "The sign-up form", series: "Closes the gap", plat: "Instagram 1:1 (also X, Threads)",
    ig: "The sign-up form.\n\nEmail: not needed. Password: not needed. Mother's maiden name: absolutely not.\n\nFarside pairs with a QR code on your Mac and a yes. No account.",
    x: "The Farside sign-up form:\n\nEmail: not needed\nPassword: not needed\nMother's maiden name: absolutely not\n\nScan the code on your Mac. Approve. Done.",
    threads: "Our sign-up form has zero fields. Scan a QR code on your Mac, approve, done.", tag: "Mac", hashtags: H.ig,
    alt: "A sign-up form with every field crossed out, and a QR code: scan the code on your Mac." },
  "post-07": { title: "Tiny button? The view follows you.", series: "Closes the gap", plat: "X 16:9",
    x: "Tiny button?\n\nZoom in and the view follows your pointer around the screen. No panning around.",
    threads: "Auto-follow zoom: zoom in on a tiny button and the view follows your pointer.", tag: "Mac", ig: null, hashtags: ["#farsideapp"],
    alt: "A phone zoomed in on an Export button with a big pointer on it, beside a small map of the whole Mac screen. Text: Tiny button? The view follows you." },
  "post-08": { title: "No follow-up questions", series: "Status line", plat: "Instagram 1:1 (also Threads)",
    ig: "No follow-up questions.\n\nFarside remembers when you last reached your Mac. That's all it remembers about it.\n\nControl your Mac from iPhone. Beta list in bio.",
    x: "Last reached 11:48 PM.\nWe won't ask why.",
    threads: "Last reached 11:48 PM. We won't ask why.", tag: "Mac", hashtags: H.ig,
    alt: "Mac status card: Studio Mac, last reached 11:48 PM, we won't ask why. No follow-up questions." },
  "post-09": { title: "Answer it from the couch", series: "Status line", plat: "Instagram 4:5 (also X, Threads)",
    ig: "Answer it from the couch.\n\nThe pointer is already on the button. Tap anywhere on your phone and it clicks right there.\n\nThis dialog has been open since 2019. It needed that.",
    x: "\"Are you sure you're sure?\"\n\nThis dialog has been open since 2019. Answer it from the couch.",
    threads: "What's the oldest dialog open on your Mac right now? Be honest.", tag: "Mac", hashtags: H.ig,
    alt: "Dialog open since 2019 asks Are you sure you're sure? A pointer with an orange ring clicks Yes." },
  "post-10": { title: "One human. A few agents.", series: "Built with agents", plat: "X 4:5 (also Threads)",
    x: "Farside is being built by one developer and a handful of AI coding agents.\n\nAgents: code, tests, reviews.\nHuman: decisions, testing on a real iPhone, the jokes.\n\nBuilding in public from today.",
    threads: "Building Farside with a few AI coding agents. They write code and tests; I test on a real iPhone and write the jokes. Ask me anything.", tag: "Build in public", ig: null, hashtags: ["#buildinpublic"],
    alt: "A build log: agent writes the code, agent writes the tests, agent reviews the other agents, human decides and writes the jokes. Text: One human. A few agents.", confirm: "Confirm the agent roles match how you actually work." },
  "post-11": { title: "Free at home", series: "Plans", plat: "Instagram 4:5 (also Threads)",
    ig: "Free at home. Not a trial in a trench coat.\n\nFarside is free when your iPhone and Mac share a Wi-Fi. Away from home, the Anywhere plan is coming.\n\nBeta list in bio.",
    x: "Free when your iPhone and Mac share a Wi-Fi.\nNot a trial in a trench coat.\n\nThe Anywhere plan (over the internet) is coming.",
    threads: "Free on the same Wi-Fi. Not a trial in a trench coat.", tag: "Mac", hashtags: H.ig,
    alt: "Dotted house with a phone and laptop linked by an orange dot. Free at home." },
  "post-12": { title: "Please don't walk back to your desk", series: "Status line", plat: "X 16:9",
    x: "Please don't walk back to your desk.\n\nCouch to desk: 6 m\nYou, walking: 0 m",
    threads: "What's the laziest reason you've walked back to your desk this week?", tag: "Mac", ig: null, hashtags: [],
    alt: "Dot-matrix readouts: Couch to desk 6 m, You walking 0 m. Text: Please don't walk back to your desk." },
  "post-13": { title: "Someone is controlling your Mac", series: "Status line", plat: "X 4:5 (also Threads)",
    x: "Someone is controlling your Mac…\n\nIt's you. From the couch.",
    threads: "Someone is controlling your Mac. It's you. We only look while a phone you approved is connected.", tag: "Mac", ig: null, hashtags: [],
    alt: "A Mac window marked Live with a note that says buy milk and a moving pointer. Text: Someone is controlling your Mac… It's you.", confirm: "Trust line: confirm with engineering before posting." },
  "post-14": { title: "Feel the click", series: "Closes the gap", plat: "Instagram 1:1 (also X, Threads)",
    ig: "Feel the click.\n\nTap anywhere on your iPhone and it clicks on your Mac. Your phone clicks back with a haptic, so you know it landed.\n\nControl your Mac from iPhone.",
    x: "Feel the click.\n\nTap anywhere on your phone. It clicks on your Mac, and your phone clicks back.",
    threads: "Tap anywhere, feel the click. That's the feature.", tag: "Mac", hashtags: H.ig,
    alt: "A crisp pointer at the centre of orange dotted rings like a ripple. Text: Feel the click." },
  "post-15": { title: "Beta seats", series: "Beta list", plat: "Instagram 4:5 (also X, Threads)",
    ig: "Beta seats for people who refuse to get up.\n\nFarside puts your Mac on your iPhone. Free on the same Wi-Fi.\n\nJoin the beta list: link in bio.",
    x: "Beta seats for people who refuse to get up.\n\nFarside puts your Mac on your iPhone. List in the reply.",
    threads: "Beta seats for people who refuse to get up. Link in bio.", tag: "Mac", hashtags: H.ig,
    alt: "The Farside dot pointer mark with an orange tip. Beta seats for people who refuse to get up." },
};

export const CAROUSELS = {
  c1: { title: "What if your iPhone were your Mac's trackpad?", slug: "c1-iphone-trackpad",
    ig: "What if your iPhone were your Mac's trackpad?\n\nSwipe: slide to point, tap to click, zoom that follows your pointer, and a pointer you can actually see.\n\nFree on the same Wi-Fi. Save this for the next time your Mac is across the room.",
    threads: "What if your iPhone were your Mac's trackpad? A 7-slide answer.", hashtags: H.ig,
    alt: [
      "Cover: What if your iPhone were your Mac's trackpad? A halftone hand reaching a pointer.",
      "Slide anywhere, the pointer moves: a thumb path on a phone mirrored by a pointer path on a Mac.",
      "Tap anywhere, it clicks: a tap spot on the left and orange rings around a pointer on the right.",
      "The pointer is big and sharp: a tiny Mac pointer next to the large Farside pointer.",
      "Zoom in, the view follows: a phone zoomed in on a Save button with the pointer on it.",
      "Your Mac stays put, you stay on the couch: a dotted couch linked to a laptop by an orange dot.",
      "Farside: control your Mac from iPhone. Free on the same Wi-Fi, no account. Join the beta list.",
    ] },
  c2: { title: "5 things you can do from the couch", slug: "c2-five-things-couch",
    ig: "5 things you can do from the couch (without getting up):\n\n1. Click the button your Mac has been waiting on\n2. Dictate a reply that types on your Mac\n3. Copy on the Mac, paste on your phone\n4. Answer your AI agent (beta)\n5. Read the tiny text while the view follows\n\nSend this to the person whose Mac is in the other room.",
    threads: "5 things you can do from the couch. Number 4 is for the people running coding agents.", hashtags: H.ig,
    alt: [
      "Cover: 5 things you can do from the couch, with a dotted couch.",
      "1: Click the button your Mac has been waiting on. The since-2019 dialog with Yes clicked.",
      "2: Dictate the reply. A listening card and a message that types: Sounds good, see you at 7.",
      "3: Copy on the Mac, paste on your phone. A Notes window and a phone with a Paste button.",
      "4: Answer your AI agent. A notification, Your agent needs you, with Deny and Allow. Beta.",
      "5: Read the tiny text, the view follows. A zoomed Terms page with an Accept link.",
      "Free on the same Wi-Fi. The couch approves. Beta list in bio.",
    ] },
  c3: { title: "How Farside works in 3 taps", slug: "c3-three-taps",
    ig: "How Farside works in 3 taps:\n\n1. Scan the code the Mac helper shows\n2. Approve it on the Mac (technically a click, we're counting it)\n3. Connect\n\nNo account. No router settings. Free on the same Wi-Fi.",
    threads: "Setup, in three taps. Tap two is technically a click. We're counting it.", hashtags: H.ig,
    alt: [
      "Cover: How Farside works in 3 taps, three dots labelled Scan, Approve, Connect.",
      "Tap 1: scan the code on your Mac. A QR code on a Mac window and a phone camera frame.",
      "Tap 2: approve it on the Mac. A dialog: Allow Sam's iPhone to connect? Technically a click.",
      "Tap 3: Connect. A Mac card and a big Connect button with an orange arrow.",
      "That's it: your Mac's desktop on a phone with the pointer on a button.",
      "Scan. Approve. Connected. No account, free on the same Wi-Fi. Join the beta list.",
    ] },
};

export const VIDEOS_COPY = {
  v01: { title: "Contact", hook: "Sound off? Watch the dot",
    beats: "0.0 s hand already moving, hook on screen · 1.25 s contact: ember ripple, Gap 0 cm · connected · 1.5 s Connected. That's the whole product. · 3.95 s second tap: click · 4.35 s Your Mac is far. Your reach isn't. · 7.45 s end card · 9.6 s loops back to the hook",
    caption: "Watch the dot. That's the whole product.\n\nFarside: see and control your Mac from your iPhone. The whole screen is a trackpad.",
    x: "Your Mac is far. Your reach isn't.\n\nFarside: see and control your Mac from your iPhone.",
    tiktok: H.tt, ig: H.ig,
    sound: "Minimal and tactile: a low synth drone that swells as the finger closes in, one soft click at 1.25 s, a second at 3.95 s. Pick a slow ambient or lo-fi bed from TikTok's Commercial Music Library / Meta Sound Collection, or record a real tap on glass and name it “farside · the click”. No vocals over the hook." },
  v02: { title: "POV: your Mac is at home and you're on the train", hook: "POV your Mac is at home and you're on the train",
    beats: "0 s POV hook, train lights streaking, Anywhere plan · coming chip · 2.45 s You forgot to hit Export · 3.1 s pointer travels · 5.8 s tap, ember ripple · 6 s Exported from seat 14B · 7.9 s Your Mac is far · 10.7 s Away from home needs the Anywhere plan. Coming soon. Free on the same Wi-Fi. · 13 s end card",
    caption: "POV: your Mac is at home and you're on the train.\n\nAway-from-home access is the Anywhere plan, coming soon. On the same Wi-Fi, Farside is free.",
    x: "POV: your Mac is at home and you're on the train.\n\n(The Anywhere plan is coming. Same Wi-Fi is free.)",
    tiktok: H.tt, ig: H.ig,
    sound: "Commuter calm: soft rhythmic train-track pulse, muted piano or lo-fi chords, a tiny notification-style ding on Exported (make your own, not Apple's). A chill lo-fi or ambient track from the business library fits; POV trends usually ride a quiet beat." },
  v03: { title: "Distance: 8,421 km to 0 km", hook: "Distance to your Mac 8,421 km",
    beats: "0 s counter already falling · 3.2 s 0 km, ember ripple, Connected · 3.65 s (we rounded) · 5.05 s Your Mac is far · 7.5 s end card with Across the internet: Anywhere plan · coming · 9.35 s counter resets for the loop",
    caption: "Distance to your Mac: 8,421 km → 0 km. (We rounded.)\n\nAcross the internet is the Anywhere plan, coming soon. Same Wi-Fi is free.",
    x: "Distance to your Mac: 8,421 km.\nDistance to your Mac with Farside: 0 km.\n\n(We rounded. Anywhere plan coming.)",
    tiktok: H.tt, ig: H.ig,
    sound: "Countdown tension: fast ticking or an arpeggiated synth that accelerates to 3.2 s, a hard stop and one deep hit at 0 km, then silence for the deadpan “(we rounded)”. Use a build-and-drop track from the business library, or a clock-tick you record." },
  v04: { title: "Someone is controlling your Mac… it's you", hook: "Someone is controlling your Mac…",
    beats: "0 s pointer already moving on its own · 1.2 s clicks Notes, types buy milk · 3.45 s renames a file: final final v2 · 4.9 s zooms out into a phone · 5.3 s It's you. From the couch · 7.6 s We only look while a phone you approved is connected · 9.7 s end card",
    caption: "Someone is controlling your Mac…\n\nIt's you. From the couch. Farside: see and control your Mac from your iPhone.",
    x: "Someone is controlling your Mac…\n\nIt's you.",
    tiktok: H.tt, ig: H.ig,
    sound: "Suspense-then-reveal: tense low strings or a thriller-style pulse for 0 to 4.9 s, a record-scratch or abrupt cut to silence at the zoom-out, then something light and smug for “It's you.” Classic mystery-reveal format; pick a cleared suspense track.",
    confirm: "Trust line on screen at 7.6 s: confirm before posting." },
  v05: { title: "The shy pointer", hook: "Reach for the pointer",
    beats: "0 s hand reaching · 1.0 s pointer dodges: It's shy the first time · 2.5 s dodges again: Still shy. Keep going · 3.95 s contact, ember ripple, Connected · 6.7 s Your Mac is far · 9.2 s end card",
    caption: "It's shy the first time.\n\nFarside: your fingertip, your Mac's pointer, one dot where they meet.",
    x: "Reach for the pointer.\n\nIt's shy the first time.",
    tiktok: H.tt, ig: H.ig,
    sound: "Cartoon-deadpan: a playful plucked or pizzicato loop, a quick “whoosh” on each dodge, a warm chord on contact. Comedy-timing tracks from the business library work; keep it light, not slapstick." },
  v06: { title: "Agent needs you (beta)", hook: "Your agent has been waiting 41 minutes",
    beats: "0 s terminal waiting, timer ticking, needs-input dot pulsing · 2.2 s phone slides up with Your agent needs you, beacon rings, Beta tag · 4.0 s tap · 5.2 s tap Allow · 5.35 s Tap Allow. Back to your life. · 8.1 s Agent needs you, beta, for AI coding agents on your Mac · 10.6 s end card",
    caption: "Your agent has been waiting 41 minutes.\n\nAgent needs you (beta): when your AI coding agent stops to ask, your phone taps you. Answer from the couch.",
    x: "Your agent has been waiting 41 minutes.\n\nFarside's “agent needs you” (beta) taps you when your coding agent stops to ask.",
    tiktok: ["#farsideapp", "#aicoding", "#developer", "#techtok", "#buildinpublic"], ig: ["#farsideapp", "#aicoding", "#developer", "#macos", "#buildinpublic"],
    sound: "Office ambient to relief: a soft ticking clock and keyboard room tone, a gentle phone buzz at 2.2 s (record your own, not Apple's chime), an upbeat resolve after Allow. Productivity or “day in the life” style tracks fit." },
  v07: { title: "Talk to your phone", hook: "Talk to your phone",
    beats: "0 s waveform live, Talk to your phone · 1.2 s final final v2 types into a rename field · 3.2 s tap Done · 3.4 s It types on your Mac. Even the embarrassing file names. · 6.5 s end card",
    caption: "Talk to your phone. It types on your Mac.\n\nEven the embarrassing file names.",
    x: "Talk to your phone. It types on your Mac.\n\nEven \"final final v2\".",
    tiktok: H.tt, ig: H.ig,
    sound: "Voice-first: record yourself actually saying “final final v2” in a flat, tired voice (real voice beats any track), over a quiet lo-fi bed. If you use a track, leave space for the spoken line." },
};

export const THREAD = [
  { t: "Your Mac is far. Your reach isn't.\n\nFarside is here: see and control your Mac from your iPhone. The whole screen is a trackpad.", media: "videos/x-16x9/v01-contact-x-1920x1080.mp4" },
  { t: "Setup is three taps: the Mac helper shows a QR code, you scan it with your iPhone, you approve it on the Mac.\n\nNo account. No email. No router settings.", media: "carousels/c3-three-taps/c3-01-1080x1350.png" },
  { t: "The whole screen is a trackpad. Slide to point, tap anywhere to click, and your phone clicks back with a haptic so you know it landed.", media: "posts/p14-feel-the-click-ig-1080x1080.png" },
  { t: "The pointer is big and sharp, drawn by your phone instead of a shrunken Mac cursor.\n\nZoom in and the view follows it around the screen.", media: "posts/p07-follow-zoom-x-1600x900.png" },
  { t: "Talk to your phone and it types on your Mac.\n\nCopy on one, paste on the other: the clipboard works both ways.", media: "posts/p03-voice-ig-1080x1350.png" },
  { t: "Agent needs you (beta): when your AI coding agent stops to ask a question, Farside taps you on the shoulder. Answer from wherever you're sitting.", media: "posts/p05-agent-beta-x-1600x900.png" },
  { t: "Free when your iPhone and Mac are on the same Wi-Fi.\n\nReaching your Mac over the internet is the Anywhere plan: [coming soon / live now: pick the true one on the day].", media: "posts/p11-free-at-home-ig-1080x1350.png" },
  { t: "Built by one developer and a few AI coding agents. The agents write code and tests. The human tests on a real iPhone, makes the calls, and writes the jokes.", media: "posts/p10-built-with-agents-x-1080x1350.png" },
  { t: "Works on iPhone and iPad. It remembers when you last reached your Mac.\n\nIt has no follow-up questions.", media: "posts/p08-last-reached-ig-1080x1080.png" },
  { t: "Get Farside: iPhone app " + "[APP STORE LINK]" + " · Mac helper " + "[MAC DOWNLOAD LINK]" + "\n\nThen tell me the laziest reason you ever walked back to your desk.", media: null, note: "Post this as the reply that carries the links (links cost reach in the main posts)." },
];

// 14-day calendar. Day 1 = Tue 29 Sep 2026. Times are Eastern (a North American audience); shift to your audience after week 1.
export const CALENDAR = [
  { d: 1, date: "Tue 29 Sep", theme: "Hello: the contact moment", items: [
    ["Setup", "All", "Avatar, X header, bios, links, pins (see bios-and-handles.md). Business account on TikTok if you want the bio link on day one.", "—"],
    ["X", "9:00", "V01 contact (16:9) + launch-of-account line; link to the beta list in the first reply. Pin it.", "Teaser"],
    ["Threads", "10:00", "P01 reach hero + “What would you do from the couch first?” (topic: Mac)", "Teaser"],
    ["X", "13:00", "P10 One human, a few agents: the build-in-public intro", "BTS"],
    ["Instagram", "18:00", "Reel V01 contact (cover: v01 cover). Pin.", "Teaser"],
    ["TikTok", "19:00", "V01 contact", "Teaser"],
    ["All", "—", "20-minute reply block: answer every comment; reply under 5 to 10 posts from Mac, iOS-dev and AI-coding accounts", "Community"] ] },
  { d: 2, date: "Wed 30 Sep", theme: "The trackpad", items: [
    ["X", "9:00", "P12 Please don't walk back to your desk", "Meme"],
    ["Threads", "9:30", "Question: “Laziest reason you walked back to your desk this week?” + P12", "Community"],
    ["Instagram", "12:00", "Carousel C1 What if your iPhone were your Mac's trackpad?", "Feature"],
    ["TikTok", "18:00", "V05 shy pointer", "Meme"],
    ["X", "15:00", "Reply block + one quote-post of a relatable Mac complaint (no dunking)", "Community"] ] },
  { d: 3, date: "Thu 1 Oct", theme: "It's you", items: [
    ["Instagram", "9:00", "Reel V04 someone is controlling your Mac", "Meme"],
    ["X", "9:30", "V04 cut (16:9): Someone is controlling your Mac… It's you.", "Meme"],
    ["Threads", "10:00", "P13 + the trust line (confirm wording first)", "Feature"],
    ["TikTok", "14:00", "V04 someone is controlling your Mac", "Meme"],
    ["X", "16:00", "BTS: a short thread on one thing an agent got wrong today and how you caught it (real screenshot)", "BTS"] ] },
  { d: 4, date: "Fri 2 Oct", theme: "Big pointer", items: [
    ["X", "9:00", "P02 Big pointer energy", "Feature"],
    ["Threads", "10:00", "P02 + “That's the post.”", "Meme"],
    ["Instagram", "18:00", "P02 Big pointer energy (feed)", "Feature"],
    ["X", "13:00", "Reply block", "Community"] ] },
  { d: 5, date: "Sat 3 Oct", theme: "Zero fields", items: [
    ["TikTok", "10:00", "V03 distance counter", "Teaser"],
    ["X", "10:30", "P06 The sign-up form", "Meme"],
    ["Threads", "11:00", "P06 + “Our sign-up form has zero fields.”", "Meme"] ] },
  { d: 6, date: "Sun 4 Oct", theme: "Voice", items: [
    ["TikTok", "9:00", "V07 talk to your phone", "Feature"],
    ["Instagram", "18:00", "Reel V03 distance counter", "Teaser"],
    ["X", "11:00", "V03 (vertical) + “(we rounded)” line", "Teaser"] ] },
  { d: 7, date: "Mon 5 Oct", theme: "Agents (beta)", items: [
    ["X", "9:00", "P05 Your agent needs you + 3-post thread: what the beta does, what it doesn't do yet, what to ask for", "Feature"],
    ["Threads", "10:00", "P05 + “What do you let your agents do without asking?”", "Community"],
    ["TikTok", "13:00", "V06 agent needs you", "Feature"],
    ["X", "15:00", "Beta-list CTA reply to your own P05 thread (link in reply)", "CTA"] ] },
  { d: 8, date: "Tue 6 Oct", theme: "The couch list", items: [
    ["Instagram", "12:00", "Carousel C2 5 things you can do from the couch", "Feature"],
    ["X", "9:00", "V06 (vertical) agent needs you", "Feature"],
    ["Threads", "10:00", "C2 as a multi-image post", "Feature"],
    ["X", "14:00", "BTS: “Week 1 of building in public”: what you shipped, one mistake, one question", "BTS"] ] },
  { d: 9, date: "Wed 7 Oct", theme: "Real footage", items: [
    ["TikTok", "14:00", "FILM YOURSELF: split screen, thumb on iPhone left, Mac pointer moving right, one click. No music, real taps. This is the proof shot.", "Feature"],
    ["Instagram", "18:00", "Reel V07 talk to your phone", "Feature"],
    ["X", "9:00", "P03 Talk to your phone", "Feature"],
    ["Threads", "10:00", "“What's the worst file name you've ever dictated?” + P03", "Community"] ] },
  { d: 10, date: "Thu 8 Oct", theme: "Since 2019", items: [
    ["Instagram", "9:00", "P09 Answer it from the couch", "Meme"],
    ["X", "9:30", "P09 + the 2019 dialog line", "Meme"],
    ["Threads", "10:00", "Poll: “Oldest dialog open on your Mac right now: days / weeks / years / I refuse to look”", "Community"],
    ["TikTok", "15:00", "V02 POV: your Mac is at home and you're on the train", "Teaser"] ] },
  { d: 11, date: "Fri 9 Oct", theme: "Zoom", items: [
    ["Instagram", "18:00", "Reel V06 agent needs you", "Feature"],
    ["X", "9:00", "P07 Tiny button? The view follows you.", "Feature"],
    ["Threads", "10:00", "P07", "Feature"],
    ["X", "13:00", "Reply block + answer every beta-list question publicly", "Community"] ] },
  { d: 12, date: "Sat 10 Oct", theme: "Free at home", items: [
    ["TikTok", "10:00", "C2 as a photo-mode carousel (cheap test; video usually wins on TikTok)", "Feature"],
    ["X", "10:30", "P11 Free at home. Not a trial in a trench coat.", "CTA"],
    ["Threads", "11:00", "P11", "CTA"] ] },
  { d: 13, date: "Sun 11 Oct", theme: "Build in public", items: [
    ["TikTok", "9:00", "FILM YOURSELF: 20 s talking head, “I'm building a Mac remote with AI agents. Here's what they got wrong this week.” Show a real screen, hide notifications.", "BTS"],
    ["Instagram", "18:00", "Reel V02 POV train", "Teaser"],
    ["X", "11:00", "P14 Feel the click", "Feature"] ] },
  { d: 14, date: "Mon 12 Oct", theme: "Beta list", items: [
    ["Instagram", "12:00", "Carousel C3 How Farside works in 3 taps (pin it)", "Feature"],
    ["X", "9:00", "P15 Beta seats for people who refuse to get up (link in reply)", "CTA"],
    ["Threads", "10:00", "P15 + “What should the beta test first?”", "CTA"],
    ["TikTok", "13:00", "Best performer of weeks 1 and 2, re-cut with a new first line (not a repost of the same file)", "Teaser"],
    ["All", "—", "Review: per post, 3-second hold / average watch time, sends/shares, follows. Double down on the top hook next week.", "Review"] ] },
];

export const CHEAT = {
  colors: [["Void", "#050505", "Every background"], ["Panel", "#121212", "Cards, UI plates"], ["Bone", "#EDE8DF", "Type, dots, pointer"], ["Ash", "#8C877F", "Secondary type, captions"], ["Dim", "#4A4742", "Decoration only, never text"], ["Ember", "#FF5B1F", "Contact only: touch, click, live, the mark's tip"]],
};
