// Build-time CSS poster for the curtain looks: the shader's first frame (time T0) flattened to CSS gradients, so
// the page paints the same picture before WebGL starts, and Reduce Motion / Save-Data see it for good.
// scripts/build.ts appends this to the home page's stylesheet.

import { BLOOM, DOT_CELL, DOT_COLS, T0, band, curtainColor, isDotColumn, sway } from "./pattern";

const STEPS = 72;
/** Mean of the shader's shimmer term (.62 + .38 * noise) and its final gain for the curtains. */
const SHIMMER = 0.81, GAIN = 1.3;
const BASE = 5;

const smoothstep = (a: number, b: number, x: number) => {
  const t = Math.min(1, Math.max(0, (x - a) / (b - a)));
  return t * t * (3 - 2 * t);
};
const pct = (v: number) => `${+(v * 100).toFixed(1)}%`;

function colours(spectrum: boolean, cols: number | null, dots: boolean): string {
  const y = 0.25;
  const stops: string[] = [];
  for (let i = 0; i <= STEPS; i++) {
    const x = i / STEPS;
    const inDots = cols !== null && isDotColumn(Math.min(cols - 1, Math.floor(x * cols)));
    const xs = x + sway(y, T0);
    const { b, n } = band(xs, T0);
    const c = curtainColor(xs, n, T0, spectrum);
    const k = (dots ? (inDots ? 1.35 : 0) : inDots ? 0 : 1) * b * SHIMMER * GAIN;
    const rgb = c.map((v) => Math.min(255, Math.round(BASE + v * k * 255)));
    stops.push(`rgb(${rgb.join(",")}) ${pct(x)}`);
  }
  return `linear-gradient(90deg,${stops.join(",")})`;
}

/** The fall-off from the top (mean hanging length) and the fade at the hero's bottom, as an alpha mask. */
function fall(): string {
  const stops: string[] = [];
  for (let i = 0; i <= 20; i++) {
    const y = i / 20;
    const f = (1 - smoothstep(0, 0.72, y)) ** 2 * (1 - smoothstep(0.74, 1, y));
    stops.push(`rgba(0,0,0,${Math.min(1, f * 1.15).toFixed(3)}) ${pct(y)}`);
  }
  return `linear-gradient(${stops.join(",")})`;
}

function dotColumns(cols: number): string {
  const stops: string[] = [];
  for (let g = 0; g < cols; g++) {
    const a = isDotColumn(g) ? "#000" : "transparent";
    stops.push(`${a} ${pct(g / cols)} ${pct((g + 1) / cols)}`);
  }
  return `linear-gradient(90deg,${stops.join(",")})`;
}

function rules(cols: number, cell: number): string {
  const mask = fall();
  const dotMask = `radial-gradient(circle closest-side,#000 60%,transparent 84%) 0 0/${cell}px ${cell}px,${dotColumns(cols)},${mask}`;
  const out: string[] = [];
  for (const [look, spectrum] of [["spectrum", true], ["aurora", false]] as const) {
    out.push(`.hero-bg[data-bg="${look}"]::before{background:${colours(spectrum, cols, false)};-webkit-mask:${mask};mask:${mask}}`);
    out.push(`.hero-bg[data-bg="${look}"]::after{background:${colours(spectrum, cols, true)};-webkit-mask:${dotMask};-webkit-mask-composite:source-in;mask:${dotMask};mask-composite:intersect}`);
  }
  return out.join("\n");
}

const mix = (a: number[], b: number[], t: number) => a.map((v, i) => v + (b[i]! - v) * t);

/** The bloom as a radial gradient (petals averaged out) under the LED grid, fading out at the hero's bottom. */
function bloomRule(tile: number): string {
  // The shader's radius is a fraction of the hero's larger side; the hero is about a screen wide and 1.2 tall.
  const R = `${BLOOM.r} * max(100vw, 120svh)`;
  const stops: string[] = [];
  for (let i = 0; i <= 16; i++) {
    const r = i / 10;
    const I = Math.exp(-r * r * 2.6);
    let c = mix([0.4, 0.04, 0.03], [1, 0.357, 0.122], smoothstep(0.04, 0.35, I));
    c = mix(c, [1, 0.64, 0.2], smoothstep(0.35, 0.72, I));
    c = mix(c, [1, 0.86, 0.48], smoothstep(0.72, 1, I));
    const rgb = c.map((v) => Math.min(255, Math.round(BASE + v * I * 0.97 * 255)));
    stops.push(`rgb(${rgb.join(",")}) calc(${R} * ${r})`);
  }
  const grid = `repeating-linear-gradient(90deg,#050505 0 1.6px,transparent 1.6px ${tile}px),repeating-linear-gradient(0deg,#050505 0 1.6px,transparent 1.6px ${tile}px)`;
  const mask = "linear-gradient(#000 62%,transparent 94%)";
  return `.hero-bg[data-bg="bloom"]::before{background:${grid},radial-gradient(circle at ${pct(BLOOM.x)} ${pct(BLOOM.y)},${stops.join(",")});-webkit-mask:${mask};mask:${mask}}`;
}

export function posterCss(): string {
  return `/* hero-bg poster, generated by src/hero-bg/poster.ts */\n${rules(DOT_COLS.wide, DOT_CELL.wide)}\n${bloomRule(16)}\n@media (max-width:639px){\n${rules(DOT_COLS.narrow, DOT_CELL.narrow)}\n${bloomRule(12)}\n}\n`;
}
